version: '3'

services:
  porter-http:
    restart: on-failure
    image: porter:latest
    container_name: porter-http
    build:
      context: ../../..
      dockerfile: deploy/docker/porter/Dockerfile
    ports:
      # Default Porter port
      - "80:9155"
    volumes:
      - .:/code
      - ~/.local/share/nulink:/nulink
    command: ["nulink", "porter", "run",
              "--eth-provider", "${WEB3_PROVIDER_URI}",
              "--network", "${NULINK_NETWORK}",
              "--allow-origins", "${PORTER_CORS_ALLOW_ORIGINS}"]  # empty string if env var not defined which translates to CORS not enabled by default

  porter-https:
    restart: on-failure
    image: porter:latest
    container_name: porter-https
    ports:
      # Default Porter port
      - "443:9155"
    volumes:
      - .:/code
      - ~/.local/share/nulink:/nulink
      - "${TLS_DIR}:/etc/porter/tls/"
    command: [ "nulink", "porter", "run",
               "--eth-provider", "${WEB3_PROVIDER_URI}",
               "--network", "${NULINK_NETWORK}",
               "--tls-key-filepath", "/etc/porter/tls/key.pem",
               "--tls-certificate-filepath", "/etc/porter/tls/cert.pem",
               "--allow-origins", "${PORTER_CORS_ALLOW_ORIGINS}"]  # empty string if env var not defined which translates to CORS not enabled by default

  porter-https-auth:
    restart: on-failure
    image: porter:latest
    container_name: porter-https-auth
    ports:
      # Default Porter port
      - "443:9155"
    volumes:
      - .:/code
      - ~/.local/share/nulink:/nulink
      - "${TLS_DIR}:/etc/porter/tls/"
      - "${HTPASSWD_FILE}:/etc/porter/auth/htpasswd"
    command: [ "nulink", "porter", "run",
               "--eth-provider", "${WEB3_PROVIDER_URI}",
               "--network", "${NULINK_NETWORK}",
               "--tls-key-filepath", "/etc/porter/tls/key.pem",
               "--tls-certificate-filepath", "/etc/porter/tls/cert.pem",
               "--basic-auth-filepath", "/etc/porter/auth/htpasswd",
               "--allow-origins", "${PORTER_CORS_ALLOW_ORIGINS}"]  # empty string if env var not defined which translates to CORS not enabled by default
