name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
      - uses: akaihola/darker@1.4.2
        with:
          options: "--check --diff --isort"
          version: "1.4.2"
